# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest
stages:
  - test
  - package
  - deploy

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

.unit tests: &unit-test-definition
  stage: test
  script:
    - pip install unittest-xml-reporting
    - python -m xmlrunner -o junit-reports
  artifacts:
    reports:
      junit: junit-reports/*.xml

unit tests merge request:
  <<: *unit-test-definition
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.py"
      - "*.py"

unit tests:
  <<: *unit-test-definition
  only:
    refs:
      - master
      - develop

# pep8 runs different tests for different Python versions
.style check:
  stage: test
  variables:
    GIT_LFS_SKIP_SMUDGE: "1"
  script:
    - pip install pylint
    - pylint -e all -d invalid-name,missing-docstring --confidence HIGH,INFERENCE --generated-members="numpy.*,torch.*" -f colorized ./*
    - echo "PyLint exit code:" $?
  only:
    refs:
      - master
      - develop
      - merge_requests
    changes:
      - "**/*.py"
      - "*.py"

checkin deliverables: # This is not needed anymore
  stage: package
  variables:
    GIT_LFS_SKIP_SMUDGE: "1"
  before_script:
    - pip install nbconvert
  script:
    - jupyter nbconvert --to html webpages/progress_checkin/"Project Check-in".ipynb --TagRemovePreprocessor.remove_cell_tags='{"remove_cell"}' --template full --output index
    - mkdir -p progress_checkin
    - mv webpages/progress_checkin/index.html progress_checkin/index.html
  artifacts:
    name: "check-in_gradescope_upload"
    paths:
      - progress_checkin
    expire_in: 10 mins
  only:
    - master

final deliverables:
  stage: package
  before_script:
    - pip install nbconvert
  script:
    - jupyter nbconvert --to html webpages/project_webpage/presentation.ipynb --TagRemovePreprocessor.remove_cell_tags='{"remove_cell"}' --template full --output index
    - rm webpages/project_webpage/presentation.ipynb
    - mv webpages/project_webpage project_webpage
    - rm -rf webpages poster .git .git*
  artifacts:
    name: "gradescope_upload"
    paths:
      - ${CI_PROJECT_DIR}
  only:
    - master
    - final-deliverables

pages:
  image: alpine:latest
  stage: deploy
  script:
    - mv gradescope_upload/project_webpage public
    - mv progress_checkin/index.html public/progress.html
    - cp install.sh public/install.sh
    - cp poster.pdf public/poster.pdf
  artifacts:
    paths:
      - public
    expire_in: 20 mins
  only:
    - master
  dependencies:
    - final deliverables
    - checkin deliverables
