# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

unit tests:
  stage: test
  script:
    - pip install unittest-xml-reporting
    - python -m xmlrunner -o junit-reports
  artifacts:
    reports:
      junit: junit-reports/*.xml
  only:
    - master
    - develop
    - merge_requests

# pep8 runs different tests for different Python versions
style check:
  stage: test
  script:
    - pip install pylint
    - pylint -d all ./*
  allow_failure: true
  only:
    - merge_requests