# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pip install unittest-xml-reporting
    - python -m xmlrunner -o junit-reports
  artifacts:
    reports:
      junit: junit-reports/TEST-*.xml
  only:
  - master
  - develop
  - merge_requests

# pep8 runs different tests for different Python versions
stylecheck:
  stage: test
  script:
    - pip install pylint
    - pylint -d all ./*
  allow_failure: true
  only:
  - master
  - develop
  except:
  - merge_requests

code_quality:
  image: docker:stable
  stage: test
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
  - echo "Do nothing"
  cache:
    key: "code_quality"
  only:
  - merge_requests
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json